permalink: /:year/:month/:day/:title.html
exclude:
  - index.md
  - README.md
  - _posts/1970-01-01-draft.md

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge


plugins:
  - jekyll-paginate
paginate: 4
paginate_path: "/pages:num/"
mathjax: false
#excerpt_separator: <!-- more -->
encoding: UTF-8
title : 王很水的博客
author : 王很水
email : wanghenshui@qq.com


name: 王很水的博客
description: "majar buzz kill"
url : https://wanghenshui.github.io
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
sitesearchurl : wanghenshui.github.io
baseurl: "" 
social_media:
  github_url: https://github.com/wanghenshui
  zhihu_url: https://www.zhihu.com/people/wanghenshui
  douban_url: https://www.douban.com/people/61740133/
